### ISSUE TITLE
Core Build TODO

### ISSUE THREAD

**Issue by abock** [Microsoft/workbooks#216]
Tracking issue for splitting up the build (aka CoreBuild.proj) and removing Build.proj.

- [ ] Tests
- [ ] XVS Build Host Configuration
- [ ] Provisionator
- [ ] Windows installer
- [ ] NuGet: pack Inspector client
- [ ] NuGet: pack agent SDK
- [ ] Windows: `_KillWrenchAdbServer` before build
- [ ] Mac: `xcrun -k` before build
- [ ] Proprietary
- [ ] PDB Files
- [ ] Sign Files
- [ ] `UpdatePublicApiDocs`
- [ ] `AssemblyPublicApiDocs`
- [ ] `UpdatePublicApiDefinitions`
